name: MLOps Assignment 1
on: 
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.0
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.0
    - name: Install dependencies
      run: |
        make install
